config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  
  get 'homes/contacts'
  
  get 'homes/profiles'
  
  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
  def contacts
    
  end
  
  def profiles
    
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/contacts/index.html.erb
<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
          	<h2>Riku Kiranatama</h2>
            <%= image_tag "u.jpg", height: 204, width: 204, class: "img-circle" %>
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
           <%= form_tag do %>
           <div class="form-group">
           <label for="exampleInputEmail1">Email </label>
           <input id="email" class="form-control" name="email" type="email" placeholder="Your Email" />
           </div>
           <div class="form-group">
           <label for="exampleInputMessage1">Message</label>
           <textarea class="form-control" cols="25" id="message" name="message" rows="10" placeholder="Your Message"></textarea>
           </div>
           <button type="submit" class="btn btn-default">Submit</button>
           <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/homes/contacts.html.erb
<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
          	<h2>Riku Kiranatama</h2>
            <%= image_tag "u.jpg", height: 204, width: 204, class: "img-circle" %>
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
           <%= form_tag do %>
           <div class="form-group">
           <label for="exampleInputEmail1">Email </label>
           <input id="email" class="form-control" name="email" type="email" placeholder="Your Email" />
           </div>
           <div class="form-group">
           <label for="exampleInputMessage1">Message</label>
           <textarea class="form-control" cols="25" id="message" name="message" rows="10" placeholder="Your Message"></textarea>
           </div>
           <button type="submit" class="btn btn-default">Submit</button>
           <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/homes/index.html.erb
<div class="container">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
  </ol>

 <!-- Wrapper for slides -->
 
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "1.png", width: 1500 %>
      <div class="carousel-caption">
        Desain 1
      </div>
    </div>
    <div class="item">
      <%= image_tag "3.jpg", width: 1500 %>
      <div class="carousel-caption">
        Desain 2
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" role="navigation">
          <div class="list-group">
            <p>Hallo, saya Riku dan saya akan lulus kuliah. Salam kenal yaa..<br>
		Dan berikut ini adalah hasil desain saya.
	</br></p>
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-15 col-sm-15 main pull-right">
         <div class="panel-body">
		Facebook : riku@mail.com<br>
		Twitter : riku@mail.com<br>
		Telepon : 022-61717191<br>
		Alamat : Jl. Harapan Bangsa No. 75 Bandung<br>
</div>

app/views/homes/profiles.html.erb
<div class="container">
	<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
          	<h2>Riku Kiranatama</h2>
            <%= image_tag "u.jpg", height: 204, width: 204, class: "img-circle" %>
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
           <table  class="table table-hover table-striped display" >
             <tbody>
               <tr>
                 <td><b>Nama</b></td>
                 <td>Riku Kiranatama</td>
               </tr>
               <tr>
                 <td><b>Tempat, Tanggal Lahir</b></td>
                 <td>Jakarta, 22 November 1999</td>
               </tr>
               <tr>
                 <td><b>Jenis Kelamin</b></td>
                 <td>Wanita</td>
               </tr>
               <tr>
                 <td><b>Alamat Domisili</b></td>
                 <td>Jl. Mampang Prapatan no.12</td>
               </tr>
             </tbody>
           </table>
          </div>
        </div>
      </div>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Training Bootstrap</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application', media: 'all'%>
  </head>
  <body style="padding-top:60px;">  
  	 <div class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
          <a href=”#” class = "navbar-brand">Training Bootstrap</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", '/homes/index' %></li>
            <li><%= link_to "Profile", homes_profiles_path %></li>
            <li><%= link_to "Contact", homes_contacts_path %></li>
          </ul>
        </div>  
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<div class="container">
	<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
          	<h2>Riku Kiranatama</h2>
            <%= image_tag "u.jpg", height: 204, width: 204, class: "img-circle" %>
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
           <table  class="table table-hover table-striped display" >
             <tbody>
               <tr>
                 <td><b>Nama</b></td>
                 <td>Riku Kiranatama</td>
               </tr>
               <tr>
                 <td><b>Tempat, Tanggal Lahir</b></td>
                 <td>Jakarta, 22 November 1999</td>
               </tr>
               <tr>
                 <td><b>Jenis Kelamin</b></td>
                 <td>Wanita</td>
               </tr>
               <tr>
                 <td><b>Alamat Domisili</b></td>
                 <td>Jl. Mampang Prapatan no.12</td>
               </tr>
             </tbody>
           </table>
          </div>
        </div>
      </div>
    </div>
    </div>